### ISSUE TITLE
Windows build???

### ISSUE THREAD

**Issue by ChrisBarker-NOAA** [conda-forge/fontconfig-feedstock#18]
I'm hoping to do a Windows build of libgd, but it requires fontconfig, and there is currently no Windows build for fontconfig.

Is there a major blocker? or has just no one gotten around to getting it working?

-CHB

**Comment by ccordoba12** [comment]
I think nobody has tried to compile it on Windows, but we're happy to receive PRs for that.

**Comment by ChrisBarker-NOAA** [comment]
OK -- poking around, it's a bit unclear how mard that will be. i.e. the source doesn't seem to make any mention of how to do a Windows build. But there are mentions of Windows issues in the changelog, so ....

Meanwhile, libgd on Windows may not need it after all, so I"ll probably wait until there is compelling use case.

**Comment by pkgw** [comment]
Based on the commit history in [this fontconfig fork](https://github.com/tgoyne/fontconfig), it looks like Windows support would be somewhat painful to get going.

**Comment by ChrisBarker-NOAA** [comment]
Based on the commit history in this fontconfig fork
<https://github.com/tgoyne/fontconfig>, it looks like Windows support would
be somewhat painful to get going.


Yup -- as it turns out, I only want it for libgd. And looking closer, it
looks like libgd doesn't use it on Windows.

Which makes some sense -- Windows dies handle fonts totally differently.

-CHB

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub
<https://github.com/conda-forge/fontconfig-feedstock/issues/18#issuecomment-288104521>,
or mute the thread
