### ISSUE TITLE
Misconfigured fonts.conf for fontconfig on OSX

### ISSUE THREAD

**Issue by anntzer** [conda-forge/fontconfig-feedstock#23]
Currently, the fontconfig package on OSX ships with a /etc/fonts/fonts.conf containing the following font directory list:

```
<!-- Font directory list -->

	<dir>/usr/share/fonts</dir>
	<dir>/opt/anaconda1anaconda2anaconda3/fonts</dir>
	<dir prefix="xdg">fonts</dir>
	<!-- the following element will be removed in the future -->
	<dir>~/.fonts</dir>
```
(where /opt/anaconda1anaconda2anaconda3 gets replaced by something that depends on the env prefix at install time.)

This configuration is incorrect, as OSX actually installs system-wide fonts to /Library/Fonts and a few other places (listed at https://support.apple.com/en-us/HT201722); in particular it is unlikely to find any fonts in /usr/share/fonts).  The system-wide fonts directories should instead be added during the configure stage using --with-add-fonts, similarly to how homebrew does it (https://github.com/Homebrew/homebrew-core/blob/master/Formula/fontconfig.rb#L35).

Currently, a conda-installed fontconfig will shadow a homebrew-installed one, and make system fonts invisible.  This is particularly a problem because conda-forge's matplotlib declares fontconfig as a dependency and matplotlib will rely on fontconfig, if it is present, to query what fonts are available on the system.  (While one may argue that *fonts* should also be installed into the conda env, that seems to be a bit an extreme position, and anyways font packages are not available right now AFAIK.)

xref https://github.com/matplotlib/matplotlib/issues/10201

**Comment by jakirkham** [comment]
This is a good point. Any interest in submitting a PR?

**Comment by anntzer** [comment]
not *right now*

**Comment by pkgw** [comment]
This was actually fixed a while ago, as best I understand it. Current list of directories that come preloaded:

```
<dir>/usr/share/fonts</dir>
<dir>/opt/anaconda1anaconda2anaconda3/fonts</dir>
<dir>/System/Library/Fonts</dir>
<dir>/Library/Fonts</dir>
<dir>~/Library/Fonts</dir>
<dir>/System/Library/Assets/com_apple_MobileAsset_Font3</dir>
<dir>/System/Library/Assets/com_apple_MobileAsset_Font4</dir>
```
