### ISSUE TITLE
Update to more recent version?

### ISSUE THREAD

**Issue by m-ad** [conda-forge/fontconfig-feedstock#48]
Right now this fontconfig feedstock is based on the current "stable" version of fontconfig, 2.13.1, which was released in 2018. However, the most recent version of fontconfig is 2.13.94 (2.14 RC4) from 2021-06-28, which contains several useful fixes.

Dear maintainers, would you consider updating this feedstock to use a more recent fontconfig version? I understand if you want to stick to the old "stable" version, but given that it is quite old I see value in getting a more recent version up on conda-forge.

**Comment by Tobias-Fischer** [comment]
Hiya, I am interested in getting a newer version as well. I want graphicsmagick on osx-arm64 (see https://github.com/conda-forge/graphicsmagick-feedstock/pull/17), which in turn needs gnuplot, which needs fontconfig .. however, the gnuplot tests fail with the old fontconfig version, but pass with the latest 2.13.94. Is that enough of a justification? :)

**Comment by pkgw** [comment]
Based on the release history of `fontconfig`, I think I'd be in favor of updating to 2.13.94 on the main branch at this point, as a CFEP-05 exception. This series might not be billed as "stable" but based on the rate at which it's evolving it seems clear that it's fairly solid.
