### ISSUE TITLE
Meson and autotools builds define library version on OSX differently

### ISSUE THREAD

**Issue by ryanvolz** [conda-forge/fontconfig-feedstock#57]
### Solution to issue cannot be found in the documentation.

- [X] I checked the documentation.

### Issue

Seeing this in [recent CI runs](https://dev.azure.com/conda-forge/feedstock-builds/_build/results?buildId=472226&view=logs&jobId=9c5ef928-2cd6-52e5-dbe6-9d173a7d951b&j=9c5ef928-2cd6-52e5-dbe6-9d173a7d951b&t=c66c4975-bbef-551b-2ee6-85005a231b12):
```
2022-03-10T23:13:22.0860040Z dyld: Library not loaded: @rpath/libfontconfig.1.dylib
2022-03-10T23:13:22.0862970Z   Referenced from: /Users/runner/miniforge3/conda-bld/gnuradio_1646952491112/_h_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_/lib/libpangocairo-1.0.0.dylib
2022-03-10T23:13:22.0864990Z   Reason: Incompatible library version: libpangocairo-1.0.0.dylib requires version 14.0.0 or later, but libfontconfig.1.dylib provides version 13.0.0
```
This `pango` was built against the autotools-built `fontconfig 2.13.96-*_0` which apparently defined the library version as "14" on OSX, but the installed `fontconfig` for this CI run is the most recent meson-built one `fontconfig 2.13.96-*_2` which defines the library version as "13" on OSX. I don't know which one the upstream developers intend. It's evident how this is defined [with meson](https://gitlab.freedesktop.org/fontconfig/fontconfig/-/blob/main/meson.build#L20), but I haven't done the deciphering of the autotools build system to figure the corresponding part there.

I'm not sure if the solution is to patch the `fontconfig` package to change the OSX library version number to match the old autotools build, or if we should just bite the bullet, keep `fontconfig` as it is, and recompile everything that links against `fontconfig`. Opinions are very much welcome.

### Installed packages

```shell
N/A
```

### Environment info

```shell
N/A
```

**Comment by pkgw** [comment]
See also #54, discussion in #53. I've been leaning towards rebuilding, but I'm open to alternative opinions. Note that if we rebuild, we should (I think ...) maintain compatibility with the older packages since the minimum required version of the resulting artifacts goes *down*.

There are enough affected packages that a migrator might be called for, but we've rebuilt cairo and poppler which I think has helped out some high-impact users.

**Comment by ryanvolz** [comment]
Gah, didn't look around enough before filing. I'll take a gander at the existing threads.

**Comment by pkgw** [comment]
I'm going to reopen #54 and close this issue since the latter has some useful lists of packages that might be affected.
