### ISSUE TITLE
Error 133 when build fontconfig with OSX

### ISSUE THREAD

**Issue by Massaguana** [conda-forge/fontconfig-feedstock#9]
Hello,

having problems to build fonconfig with OSX 10.11.6

What i do:

`cd ${CMPL} 
tar xjpf ../source/fontconfig-2.12.1.tar.bz2
cd fontconfig-2.12.1
./configure --prefix=${TARGET} --with-add-fonts=/Library/Fonts,~/Library/Fonts --enable-iconv --with-libiconv-lib=${TARGET}/lib --with-libiconv-includes=${TARGET}/include --with-libiconv=${TARGET}/bin --enable-static --enable-shared=no --enable-libxml2 --disable-docs
make clean
make -j 4 && make install`

Result:
`dyld: lazy symbol binding failed: Symbol not found: _mkostemp
Referenced from: /Volumes/Ramdisk/compile/fontconfig-2.11.1/fc-cache/fc-cache (which was built for Mac OS X 10.12)
Expected in: /usr/lib/libSystem.B.dylib

dyld: Symbol not found: _mkostemp
Referenced from: /Volumes/Ramdisk/compile/fontconfig-2.11.1/fc-cache/fc-cache (which was built for Mac OS X 10.12)
Expected in: /usr/lib/libSystem.B.dylib

/bin/sh: line 1: 7966 Trace/BPT trap: 5 fc-cache/fc-cache -s -f -v
make[2]: *** [install-data-local] Error 133
make[1]: *** [install-am] Error 2
make: *** [install-recursive] Error 1
`

Any ideas?

**Comment by ocefpaf** [comment]
@Massaguana `conda-forge` cannot give support for builds beyond our infrastructure. (It is already complicated enough to do that within our infrastructure :wink:)
